name: Päivitä ruokalista

on:
  schedule:
    # Ajetaan ma-pe klo 7:00 Suomen aikaa (5:00 UTC)
    - cron: '0 5 * * 1-5'
  workflow_dispatch:  # Voit myös ajaa käsin GitHubista

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Asenna Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Asenna riippuvuudet
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps chromium

      - name: Generoi index.html
        run: python generate.py

      - name: Deploy Netlifyyn
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=.
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
